hw10 v1.0
OlivkaFromHell/homework_epam pull request #3
Opened 2022-01-04 13:01 UTC by OlivkaFromHell

2022-01-04 21:31 UTC, megagnom37 requested changes
Первое ревью - можно править

2022-01-04 21:31 UTC, megagnom37 commented on hw10/stonks.py
> +    companies_data = parse_pages()
Парсер все таки неплохо было бы обернуть в класс

2022-01-04 21:31 UTC, megagnom37 commented on hw10/stonks.py
> +            json.dump(sorted_companies, f)
По сути код дублируется в этих классах - можно как то это обобщить.
И ты это делаешь в init все. Смысл в классе теряется - а точнее в инстансах которые ты создаешь ниже

2022-01-04 21:31 UTC, megagnom37 commented on hw10/stonks.py
> +            list_with_data = executor.map(get_company_info, [(link, growth) for link, growth in company_links[page]])
Почему нельзя сразу запустить получение информации для всех компаний?
Почему ты делаешь это постранично - у сайта есть ограничение не количество запросов и он блочит подозрительные DDOS действия?

2022-01-04 21:31 UTC, megagnom37 commented on hw10/stonks.py
> +                               'potential profit': potential_profit}
Мне кажется стоит создать класс для компании в котором хранятся все эти поля - таскать такой большой дикт не лучшая идея (читаемость страдает).

2022-01-04 21:31 UTC, megagnom37 commented on hw10/stonks.py
> +    return round(get_usd_value() * cost, 2)
Зачем при обработке каждой компании запрашивать в инете цену на доллар ?
Достаточно один раз запросить когда ты считал уже все цены компаний

2022-01-07 22:10 UTC, megagnom37 approved these changes
Проверил - можно не править

2022-01-07 22:10 UTC, megagnom37 commented on hw10/stonks.py
> +        company_links = get_list_of_pages_with_link_and_growth()
Ты сделал класс с парсером и оставил все функции вне его?
Почему ты не добавил их в класс - идея класса в том чтобы объединить по смыслу набор атрибутов и функций.

2022-01-07 22:10 UTC, megagnom37 commented on hw10/stonks.py
> +    return name, price, code, p_e, annual_growth, potential_profit
Почему не возвращать объект класса Company?

2022-01-07 22:10 UTC, megagnom37 commented on hw10/stonks.py
> +    data = Parser().info
Странно - почему юзать атрибут инфо а не вызвать метод parse что логичнее

2022-01-07 22:10 UTC, megagnom37 commented on hw10/stonks.py
> +        self.update({'potential profit': potential_profit})
Выглядит максимально странно =/
Либо юзать pydantic - либо уж оставь тогда dict как было

2022-01-10 17:30 UTC, olivka86 commented on hw10/stonks.py
> +        self.update({'potential profit': potential_profit})
Взял на вооружение

2022-01-10 17:30 UTC, OlivkaFromHell commented on hw10/stonks.py
> +    data = Parser().info
переделал

2022-01-10 17:31 UTC, olivka86 commented on hw10/stonks.py
> +    return name, price, code, p_e, annual_growth, potential_profit
возвращаю Company, который создан с помощью pydantic

2022-01-10 17:31 UTC, OlivkaFromHell commented on hw10/stonks.py
> +        company_links = get_list_of_pages_with_link_and_growth()
перенес все функции

2022-01-11 11:40 UTC, megagnom37 approved these changes
Принято

2022-01-13 16:19 UTC, merged